# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/src-fingerprint
    # Default build flags is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.

nfpms:
  - formats:
      - deb
      - rpm
    dependencies:
      - git
    bindir: /usr/bin
    vendor: GitGuardian
    maintainer: GitGuardian <dev@gitguardian.com>
    replacements:
      linux: Linux

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-main"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: src-fingerprint
    tap:
      owner: gitguardian
      name: homebrew-tap
      branch: main
      token: "{{ .Env.PAT_GITHUB }}"
    download_strategy: CurlDownloadStrategy
    commit_author:
      name: goreleaserbot
      email: goreleaser@gitguardian.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    description: "src-fingerprint is a CLI util to easily compute the fileshas associated to a set of git repositories."
