default_stages: [commit]
repos:
  - repo: git://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: go-imports
      - id: golangci-lint
  - repo: https://github.com/Woile/commitizen
    rev: v2.17.6
    hooks:
      - id: commitizen
        # don't forget to run pre-commit install --hook-type commit-msg for this hook to run
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/mirrors-prettier # to format JSON, YAML and markdown files among others
    rev: v2.3.0
    hooks:
      - id: prettier

  - repo: https://github.com/gitguardian/gg-shield
    rev: v1.5.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [commit]
