name: goreleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Cloudsmith CLI
        run: pip install cloudsmith-cli==0.31.1

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          # To publish the release on GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          # To publish on the Homebrew tap
          PAT_GITHUB: ${{ secrets.PAT_GITHUB }}
          # To publish on Cloudsmith
          CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
